### ISSUE TITLE
Default faces example failing due to invalid syntax.

### ISSUE THREAD

**Issue by djpm05** [m5stack/micropython-m5stack#2]
Using firmware 0.2.5 on a grey (non 4MB PSRAM) M5Stack I see the following when using micro python, and the example faces code:

```
Connect WiFi: SSID:<redacted> PASSWD:<redacted> network...
..............
Connected. Network config: ('192.168.0.27', '255.255.255.0', '192.168.0.1', '209.18.47.61')
Synchronize time from NTP server ...
Device ID:30aea449bdac
Connecting M5Cloud Server....Connected!
Traceback (most recent call last):
  File "main.py", line 2, in <module>
  File "faces.py", line 18
SyntaxError: invalid syntax

FreeRTOS running on BOTH CORES, MicroPython task started on App Core.

 Reset reason: Power on reset
    uPY stack: 19456 bytes
     uPY heap: 80000/12400/67600 bytes

MicroPython ESP32_LoBo_v2.0.8 - 2017-11-04 on M5Stack with ESP32
Type "help()" for more information.
```

**Comment by 0x1abin** [comment]
hi, i try again this code, it work well, can you check it same with my code.

**Comment by djpm05** [comment]
This was user error on my part, I had imported m5stack as m5, and that’s what caused the error. I fixed my code and it’s working correctly. Sorry about that!
